Repository karunakaran186/KAVI-voice-Assitant, pull requests merged in 2022-03, with the labels that each got.

#11 Update README.md
  README.md
Labels: Gssoc 2022, level 2

#17 Added Code of Conduct
  Code_of_Conduct.md
Labels: Gssoc 2022, level 1

#32 Updated the language used in this project photo
  README.md
Labels: Gssoc 2022, level 1

#44 Update intro README.md
  README.md
Labels: Gssoc 2022, level 1

#45 Update README.md
  README.md
Labels: Gssoc 2022, level 1

#46 automated assign labelers
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto-label.json
  .github/keylabeler.yml
  .github/stale.yml
  .github/workflows/Auto_Issue_Closer.yml
  .github/workflows/approve-workflows.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/contributors.yml
  .github/workflows/greetings.yml
  .github/workflows/issue-assign.yml
  .github/workflows/stale.yml
Labels: Gssoc 2022

#67 Feature Added: Image Request Feature
  code.py
  container.jpg
Labels: Gssoc 2022, level 1

#70 Added Feature: Open Calculator, notepad and Word document.
  code.py
Labels: Gssoc 2022, level 2

#73 Update code.py
  code.py
Labels: Gssoc 2022, level 1

#75 Added a feature which will tell system health
  code.py
Labels: Gssoc 2022, level 1

#83 added the try exception blocks for open files commands
  code.py
Labels: Gssoc 2022, level 1

#97 issue 95 resolved
  README.md
  code.py
  main.py
  modules.py
  requirements.txt
Labels: Gssoc 2022, level 2

#100 Enhancement: Moved the method of fetching joke from library to API
  modules.py
Labels: Gssoc 2022, level 1

#101 Added Volume control and battery status feature
  main.py
  modules.py
Labels: Gssoc 2022, level 3

#106 Alarm addition
  modules.py
Labels: Gssoc 2022, level 1
