Repository karunakaran186/KAVI-voice-Assitant, pull requests merged in 2022-04, with the labels that each got.

#111 Fixed the Link
  README.md
Labels: GSSOC2022, level0

#109 [Doc/fixed] Updated Readme.md file
  README.md
Labels: GSSOC2022, level0

#116 Adding docstrings
  modules.py
Labels: GSSoC22, Level1

#117 Adding Docstrings
  main.py
Labels: GSSoC22, Level0
